version: '3.0'

services:
  php:
    env_file:
        -   .env
    build:
      context: ./
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_HOST: db
      DB_DATABASE: application
      DB_USER: application_user
      DB_PASSWORD: cdqNDPFkEZquVPjk

    volumes:
      - ./:/app
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: hOWswSdsEooYEZ8b
      MYSQL_DATABASE: application
      MYSQL_USER: application_user
      MYSQL_PASSWORD: cdqNDPFkEZquVPjk
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8001:80'
